spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auto_parts_directory
    username: root
    password: ethernet
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
