spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auto_parts_directory
    username: root
    password: ethernet
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
