logging:
  level: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auto_parts_directory
    username: root
    password: ethernet
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

zuul:
  debug:
    request: true
  routes:
    user-service:
      path: /api/v1/users/**
      stripPrefix: false
      serviceId: user-service
    parts-directory-service:
      path: /api/v1/producers/**
      stripPrefix: false
      serviceId: parts-directory-service

mail:
  user:
    email-address: autopart.directory@gmail.com
    email-password: 4119641196d
  smtp:
    auth-enabled: true
    tls-enabled: true
    ssl-enabled: false
    host: smtp.gmail.com
    port: 587
